version: '3.3'
services:
    astro:
      container_name: astro_vue
      ports:
        - '3511:3000'
      environment:
        - TZ=Europe/Berlin
      volumes:
        - '/home/cloudster/certificates:/opt/certs'
      image: domx4q/astro:autoGit
      tty: true # -t flag
      stdin_open: true # -i flag
      restart: always
      
      ulimits:
        nproc: 65535