name: Build and Release Vue.js App

on:
  workflow_dispatch:

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'
      - name: Install dependencies
        run: npm install
      - name: Build app
        run: npm run build
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: v$(cat package.json | jq -r '.version')
          release_name: Release $(cat package.json | jq -r '.version')
          draft: false
          prerelease: false
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist
      - name: Get release ID
        id: get_release_id
        run: echo "::set-output name=id::$(echo ${{ steps.create_release.outputs.id }} | cut -c 2-)"
      - name: Add build artifact to release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist
          asset_name: dist
          asset_content_type: application/zip
