name: Docker Image CI

on:
  push:
    branches: [ "master" ]
    paths: "Dockerfile"
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker
      run: docker login -u domx4q -p dckr_pat_XRoQfUTJZlptcmQ3hEOzTBp59Sg
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag domx4q/astro:$(date +%s)
    - name: Push the image
      run: docker push domx4q/astro -a
